cart/urls.py
from django.conf.urls import url

from cart import views

urlpatterns = [
    # 购物车
    url(r'^cart/', views.Cart, name='cart'),
    # 添加购物车
    url(r'^addtocard/', views.AddToCard, name='addtocard'),
    # 删除购物车
    url(r'^subtocard/', views.SubToCard, name='subtocard'),
]

goods/urls.py
from django.conf.urls import url

from goods import views

urlpatterns = [
    # 首页
    url(r'^index/', views.Index, name='index'),
    # 商品的详情页
    url(r'^detail/(?P<goods_id>\d+)$', views.detail, name='detail'),
    # 商品的列表页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', views.list, name='list'),
]

ttfresh/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import static

from ttfresh import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^userweb/', include('user.urls', namespace='userweb')),
    url(r'^cartweb/', include('cart.urls', namespace='cartweb')),
    url(r'^/', include('goods.urls', namespace='goods')),
    url(r'^orderweb/', include('order.urls', namespace='orderweb')),
    url(r'^backweb/', include('backweb.urls', namespace='backweb')),
    url(r'^goodweb/', include('goods.urls', namespace='goodweb')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url

from user import views

urlpatterns = [
    # 用户中心页面
    url(r'^my/', views.my, name='my'),
    # 登录页面
    url(r'^login/', views.login, name='login'),
    # 注册页面
    url(r'^register/', views.register, name='register'),
    # 登出页面
    url(r'^logout/', views.logout, name='logout'),
    # 用户中心-收货地址信息
    url(r'^address/', views.address, name='address'),
    # 用户中心-订单信息
    url(r'^userorder/', views.userorder, name='userorder'),
]

templates/goodweb/detail.html
{% extends 'base/base.html' %}
{% load static %}


    {% block title %}
        天天生鲜-商品详情
	{% endblock %}


	{% block extCSS %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% endblock %}


    {% block content %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'userweb:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'userweb:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'userweb:my' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cartweb:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'userweb:userorder' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cartweb:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for type in types %}
			            <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
        <form action="" method="post">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}" width="100%" height="100%"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em>{{ sku.price }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" sku_id="{{ sku.id }}" class="buy_btn">立即购买</a>
				<a href="javascript:;" sku_id="{{ sku.id }}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
    </form>
	</div>


	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for sku in new_skus %}
					<li>
						<a href="{{ sku.id }}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{{ sku.id }}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content" id="tab_detail">
                <dl>
                    {% for order in sku_order_comment %}
					<dt>评论时间：{{ order.update_time }}&nbsp;&nbsp;用户名:{{ order.order.user.username }}</dt>
                    <dd>评论内容:{{ order.comment }}</dd>
                    {% endfor %}
				</dl>
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.desc }}</dd>
				</dl>
			</div>

		</div>
	</div>
    {% endblock %}


	{% block footer %}
        {{ block.super }}
	{% endblock %}


	<div class="add_jump"></div>


    {% block extJS %}
        <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js'%}"></script>
    {% endblock %}

	<script type="text/javascript">
		$('#tag_detail').click(function () {
            $('#tag_comment').removeClass('active');
            $(this).addClass('active');
            $('#tab_detail').show();
            $('#tab_comment').hide();
        });

        $('#tag_comment').click(function () {
            $('#tag_detail').removeClass('active');
            $(this).addClass('active');
            $('#tab_detail').hide();
            $('#tab_comment').show();
        })
        // 预解析
        update_goods_amount();
        // 计算商品的总价格
        function update_goods_amount() {
            //获取商品的单价和数量
            // text()和html()功能差不多，text会获取em标签中的出去标签外的任何内容
            var price = $('.show_pirze').children('em').text(),
                count = $('.num_show').val();
            // 计算商品的总价
            price = parseFloat(price);
            count = parseInt(count);
            amount = price*count;
            // 设置商品的总价
            $('.total').children('em').text(amount.toFixed(2)+'元');
        }

        // 增加商品的数量
        $('.add').click(function () {
            // 获取商品的原有数量
            var count = $('.num_show').val();
            // 加1
            count = parseInt(count) + 1;
            // 重新设置商品的数量
            $('.num_show').val(count);
            // 更新商品的总价
            update_goods_amount();
        });

        // 减少商品的数量
        $('.minus').click(function () {
            // 获取商品的原有数量
            var count = $('.num_show').val();
            // 加1
            count = parseInt(count) - 1;
            if (count<=0){
                count = 1;
            };
            // 重新设置商品的数量
            $('.num_show').val(count);
            // 更新商品的总价
            update_goods_amount();
        });

        // 手动输入商品的数量
        $('.num_show').blur(function () {
            // 获取用户输入的内容
            var $count = $(this).val();
            // 判断
            if (isNaN($count) || parseInt($count) <=0 || $count.trim().length==0){
                $count = 1;
            }
            // 重新设置商品的数量
            $('.num_show').val(count);
            // 更新商品的总价
            update_goods_amount();

        });

		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$('#add_cart').click(function () {
             // 获取商品id和商品数量
            // prop attr
            var sku_id = $(this).attr('sku_id'),
                count = $('.num_show').val(),
                csrf = $('input[name="csrfmiddlewaretoken"]').val();

            // 组织参数
            var params = {'sku_id':sku_id,'count':count,'csrf':csrf};

             // 发起ajax post请求，访问/cart/add, 传递参数:sku_id count
            $.post('/cart/add',params,function (data) {

                if(data.res == 5){
                    // 添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.total_count);
                            });
			        });
                }
                else {
                    // 添加失败
                    alert(data.errmsg)
                }
            })
        })
		$('.buy_btn').click(function () {
			var sku_id = $(this).attr('sku_id'),
                count = $('.num_show').val(),
				csrf = $('input[name="csrfmiddlewaretoken"]').val();
			window.location.href = '/order/?sku_id='+sku_id+'&count='+count
        })
	</script>
        <script type="text/javascript">
            var $add_x = $('#add_cart').offset().top;
            var $add_y = $('#add_cart').offset().left;

            var $to_x = $('#show_count').offset().top;
            var $to_y = $('#show_count').offset().left;

            $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
            $('#add_cart').click(function(){
                $(".add_jump").stop().animate({
                    'left': $to_y+7,
                    'top': $to_x+7},
                    "fast", function() {
                        $(".add_jump").fadeOut('fast',function(){
                            $('#show_count').html(2);
                        });

                });
            })
        </script>

templates/goodweb/index.html
{% extends 'base/base.html' %}
{% load static %}


	{% block title %}
        天天生鲜-首页
	{% endblock %}


    {% block extCSS %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% endblock %}


    {% block extJS %}
        <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock %}


    {% block content %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'userweb:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'userweb:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'userweb:my' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cartweb:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'userweb:userorder' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goodweb:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cartweb:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners %}
				    <li><a href="{% url 'goodweb:detail' banner.sku.id %}">
                        <img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>

			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'images/adv01.jpg' %}"></a>
			<a href="#"><img src="{% static 'images/adv02.jpg' %}"></a>
		</div>
	</div>
    {% for type_list in types %}
	    <div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type_list.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type_list.title_banners %}
				    <a href="{% url 'goodweb:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'goodweb:list' type_list.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

        <div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type_list.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type_list.image_banners %}
				    <li>
					<h4><a href="{% url 'goodweb:detail' banner.sku.id %}">{{ banner.name }}</a></h4>
					<a href="{% url 'goodweb:detail' banner.sku.id %}">
                        <img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
    </div>
    {% endfor %}
    {% endblock %}


    {% block footer %}
	    {{ block.super }}
    {% endblock %}



{#        <script type="text/javascript">#}
{#            BCSlideshow('focuspic');#}
{#            var oFruit = document.getElementById('fruit_more');#}
{#            var oShownum = document.getElementById('show_count');#}
{##}
{#            var hasorder = localStorage.getItem('order_finish');#}
{##}
{#            if(hasorder)#}
{#            {#}
{#                oShownum.innerHTML = '2';#}
{#            }#}
{##}
{#            oFruit.onclick = function(){#}
{#                window.location.href = 'list.html';#}
{#            }#}
{#        </script>#}

templates/goodweb/list.html
{% extends 'base/base.html' %}
{% load static %}
	<title>天天生鲜-商品列表</title>

	{% block extCSS %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% endblock %}


    {% block content %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'userweb:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'userweb:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'userweb:my' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cartweb:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'userweb:userorder' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cartweb:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					{% for type in types %}
			            <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ good_type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in news_sku %}
					<li>
						<a href="{% url 'goodweb:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goodweb:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goodweb:list' good_type.id 1 %}" {% if sort == 'default' %} class="active"{% endif %}>默认</a>
				<a href="{% url 'goodweb:list' good_type.id 1 %}?sort=price" {% if sort == 'price' %} class="active"{% endif %}>价格</a>
				<a href="{% url 'goodweb:list' good_type.id 1 %}?sort=hot" {% if sort == 'hot' %} class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for sku in skus_page %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
                            <a href="javascript:;" class="add_goods" title="加入购物车" sku_id="{{ sku.id }}"></a>
                        </div>
				    </li>
                {% endfor %}
			</ul>

			<div class="pagenation">
				{% if skus_page.has_previous %}
				    <a href="{% url 'goodweb:list' good_type.id skus_page.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == skus_page.number %}
				        <a href="{% url 'goodweb:list' good_type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'goodweb:list' good_type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
				{% endfor %}
                {% if skus_page.has_next %}
				    <a href="{% url 'goodweb:list' good_type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
    {% endblock %}


    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js'%}"></script>
	<script type="text/javascript">
		//添加购物车
		$('.add_goods').click(function () {
			var sku_id = $(this).attr('sku_id'),
				count = 1;
			var params = {'sku_id':sku_id,'count':count}

			var add_x = $(this).offset().left;
			var add_y = $(this).offset().top;

			var to_x = $('#show_count').offset().left;
			var to_y = $('#show_count').offset().top;

			$.post('/cart/add',params,function (data) {
				if(data.res == 5){
                    // 添加成功
					$(".add_jump").css({'left':add_x+80,'top':add_y+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': to_x+7,
                        'top': to_y+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.total_count);
                            });
			        });
                } else {
                    // 添加失败
                    alert(data.errmsg)
                }
            })
        })

	</script>

    {% block footer %}
        {{ block.super }}
    {% endblock %}