cart/urls.py
from django.conf.urls import url

from cart import views

urlpatterns = [
    # 购物车
    url(r'^cart/', views.Cart, name='cart'),
    # 添加购物车
    url(r'^addtocard/', views.AddToCard, name='addtocard'),
    # 删除购物车
    url(r'^subtocard/', views.SubToCard, name='subtocard'),
]

goods/urls.py
from django.conf.urls import url

from goods import views

urlpatterns = [
    # 首页
    url(r'^index/', views.Index, name='index'),
    # 商品的详情页
    url(r'^detail/(?P<goods_id>\d+)$', views.detail, name='detail'),
    # 商品的列表页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', views.list, name='list'),
]

order/urls.py
from django.conf.urls import url

from order import views
urlpatterns = [
    # 创建订单操作
    url(r'^orderweb/', views.create, name='create'),
    # 提交订单,生成订单数据
    url(r'^commit/', views.commit, name='commit'),
    # 订单支付页面
    url(r'^pay/', views.pay, name='pay'),

]

ttfresh/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import static

from ttfresh import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^userweb/', include('user.urls', namespace='userweb')),
    url(r'^cartweb/', include('cart.urls', namespace='cartweb')),
    url(r'^/', include('goods.urls', namespace='goods')),
    url(r'^orderweb/', include('order.urls', namespace='orderweb')),
    url(r'^backweb/', include('backweb.urls', namespace='backweb')),
    url(r'^goodweb/', include('goods.urls', namespace='goodweb')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url

from user import views

urlpatterns = [
    # 用户中心页面
    url(r'^my/', views.my, name='my'),
    # 登录页面
    url(r'^login/', views.login, name='login'),
    # 注册页面
    url(r'^register/', views.register, name='register'),
    # 登出页面
    url(r'^logout/', views.logout, name='logout'),
    # 用户中心-收货地址信息
    url(r'^address/', views.address, name='address'),
    # 用户中心-订单信息
    url(r'^userorder/', views.userorder, name='userorder'),
]

cart/models.py
from django.db import models

from goods.models import GoodsSKU
from user.models import User


class CartModel(models.Model):
    user = models.ForeignKey(User, verbose_name='关联用户')  # 关联用户
    goods = models.ForeignKey(GoodsSKU, verbose_name='关联的商品')
    quantity = models.IntegerField(default=1, verbose_name='商品的数量')
    is_select = models.BooleanField(default=True, verbose_name='是否勾选商品')

    class Meta:
        db_table = 'tt_cart'
        verbose_name = '购物车'
        verbose_name_plural = verbose_name

cart/views.py
from django.http import JsonResponse
from django.shortcuts import render

from cart.models import CartModel


def Cart(request):
    # 购物车
    if request.method == 'GET':
        # user = request.user
        skus = CartModel.objects.all()

        return render(request, 'cartweb/cart.html', {'skus': skus})


def AddToCard(request):
    if request.method == 'POST':
        # 先进行验证用户是否已经登录
        user = request.user
        data = {}
        # 定义一个错误码的对应的文档
        data['code'] = '1992'
        # 如果用户已经登录，就获取用户的id
        if user.id:
            # 获取前端获得的商品的id号
            sku_id = request.POST.get('sku_id')
            count = request.POST.get('count')
            # 然后验证当前的用户是否对商品进行添加操作，对数据库进行查看
            cart = CartModel.objects.filter(user=user, sku_id=sku_id).first()
            # 如果有数据
            if cart:
                # 如果是进行添加操作，则对操作进行加1操作
                cart.quantity += 1
                cart.save()
                data['quantity'] = cart.quantity
                # 如果没有的话，是进行首次的添加操作，
            else:
                CartModel.objects.create(user=user, sku_id=sku_id)
                data['quantity'] = 1
            data['code'] = '200'
            data['msg'] = '请求成功'
            return JsonResponse(data)
        return JsonResponse(data)


def SubToCard(request):
    # 删除购物车
    if request.method == 'POST':
        user = request.user
        data = {}
        data['msg'] = '请求成功'
        # 定义一个错误码的对应的文档
        data['code'] = '1993'
        # 如果用户已经登录，就获取用户的id
        if user.id:
            # 获取前端获得的商品的id号
            sku_id = request.POST.get('sku_id')
            # 然后验证当前的用户是否对商品进行添加操作，对数据库进行查看
            card = CartModel.objects.filter(user=user, sku_id=sku_id).first()
            # 如果存在数据的话
            if card:
                # 如果数据的数量是1，那么对数据进行操作后，数据将会被删除，变为0
                if card.quantity == 1:
                    card.delete()
                    data['quantity'] = 0
                # 如果数量不是1的时候，那么操作的时候就会对数据进行减一的操作
                else:
                    card.quantity -= 1
                    card.save()
                    data['quantity'] = card.quantity
                # 定义一个代码的返回code的成功数值
                data['code'] = '200'
                return JsonResponse(data)
            # 如果数据不存在，就给返回一个数据信息
            else:
                data['msg'] = '请先添加商品'
                return JsonResponse(data)
        # 如果用户没有登录。
        else:
            data['msg'] = '用户没有登录'
            return JsonResponse(data)

templates/cartweb/cart.html
{% extends 'base/base.html' %}
{% load static %}

	{% block title %}
        天天生鲜-购物车
	{% endblock %}

    {% block extCSS %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% endblock %}

    {% block content %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'userweb:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'userweb:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'userweb:my' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cartweb:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'userweb:userorder' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goodweb:index' %}" class="logo fl">
            <img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="total_count">全部商品<em>{{ total_count }}</em>件</div>
    <form method="post" action="{% url 'orderweb:create' %}">
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    {% for sku in skus %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked></li>
		<li class="col02"><img src="{{ sku.image.url }}"></li>
		<li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}g</em></li>
		<li class="col04">{{ sku.unite }}g</li>
		<li class="col05">{{ sku.price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" sku_id="{{ sku.id }}" class="num_show fl" value="{{ sku.count }}">
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">{{ sku.amount }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}
	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total.price }}</em><br>共计<b>{{ total.count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
    </form>
    {% endblock %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
    // 计算被选中的商品的总件数和总价格、总件数、全勾选状态
    function update_page_info() {
        var total_count = 0,
            buy_amount = 0,
            buy_count = 0;
        // 获取所有被选中的商品的checkbox
        // 获取所有被选中的商品所在的ul元素
        $('.cart_list_td').each(function () {
            // 获取商品的数目和购买状态
            var buy = $(this).find('.col01 :checkbox').is(':checked'),
                count = $(this).find('.num_show').val();
            count = parseInt(count);
            // 获取价格和数量
            var price = $(this).find('.col05').html();
            price = parseFloat(price);
            // 总价
            var subtotal = count*price;

            // 累加计算商品的总件数和总价格
            total_count += count,
            buy_count += count * buy,
            buy_amount += subtotal * buy;
        });
        // 设置被选中的商品的总件数和总价格以及总件数
        $('.settlements .col03 em').html(buy_amount.toFixed(2) + '元');
        $('.settlements .col03 b').html(buy_count);
        $('.total_count em').html(total_count);
    };

    // 商品的全选和全不选
    $('.settlements').find(':checkbox').change(function () {
            // 获取全选的checkbox的选中状态
            var is_checked = $(this).prop('checked');
            // 遍历商品的对应的checkbox，设置那些checkbox的选中状态和全选的checkbox保持一致
            $('.cart_list_td').find(':checkbox').each(function () {
                $(this).prop('checked', is_checked);
            });
            // 更新页面信息
            update_page_info();
        });

    // 商品对应的checkbox状态发生改变时，设置全选checkbox的状态
    $('.cart_list_td').find(':checkbox').change(function () {
            // 获取页面上所有商品的数目
            var all_len = $('.cart_list_td').length;
            // 获取页面上所有勾选商品的数目
            var checked_len = $('.cart_list_td').find(':checked').length;
            var is_checked = true;
            if (all_len > checked_len){
                is_checked = false;
            }
            $('.settlements').find(':checkbox').prop('checked', is_checked);
            update_page_info();
        });


    // 更新购物车中商品的数量
    var error_update = false,
        count = 0;
    function update_remote_cart_info(sku_id, count) {
       var csrf = $('input[name="csrfmiddlewaretoken"]').val(),
        // 组织参数
            params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf};
        // 设置ajax请求为同步
        // 设置ajax请求为同步，此设置为全局
        $.ajaxSettings.async = false;
        // 发起ajax post请求，访问/cart/update, 传递参数:sku_id count
        // 默认发起的ajax请求都是异步的，不会等回调函数执行
        $.post('/cart/update', params, function (data) {
            if (data.res == 5){
                error_update=false;
                count = data.total_count;
            }else {
                error_update = true;
                alert('更新失败')
            }
        });
        // 设置ajax请求为异步
        $.ajaxSettings.async = true
    }


    // 购物车商品数量的增加
    $('.add').click(function () {
        // 获取商品的id和商品的数量
        var sku_id = $(this).next().attr('sku_id'),
            count = $(this).next().val();
        // 组织参数
        count = parseInt(count) + 1;
        // 更新购物车记录
        update_remote_cart_info(sku_id, count);
        // 判断更新是否成功
        if (error_update == false){
            // 更新成功
            // 获取页面上所有商品的数目
            var all_len = $('.cart_list_td').length;
            // 获取页面上所有勾选商品的数目
            var checked_len = $('.cart_list_td').find(':checked').length;
            is_checked = true;
            if (all_len > checked_len){
                is_checked = false;
            }
            $('.settlements').find(':checkbox').prop('checked', is_checked);

            // 更新商品总数
            $(this).next().val(count);
            update_page_info();

        }
    });

    // 购物车商品数量的减少
    $('.minus').click(function () {
        // 获取商品的id和商品的数量
        var sku_id = $(this).prev().attr("sku_id"),
            count = $(this).prev().val();

        // 组织参数
        count = parseInt(count) - 1;
        if (count <= 0){
            count=1;
        }

        // 更新购物车记录
        update_remote_cart_info(sku_id, count);
        // 判断更新是否成功
        if (error_update == false){
            // 更新成功
            // 获取页面上所有商品的数目
            var all_len = $('.cart_list_td').length;
            // 获取页面上所有勾选商品的数目
            var checked_len = $('.cart_list_td').find(':checked').length;
            is_checked = true;
            if (all_len > checked_len){
                is_checked = false;
            }
            $('.settlements').find(':checkbox').prop('checked', is_checked);

            // 更新商品总数
            $(this).prev().val(count);
            update_page_info();

        }
    })

    var pre_count = 0;
    $('.num_show').focus(function () {
        pre_count = $(this).val();
    })

    // 手动输入商品的数量
    $('.num_show').blur(function () {
        // 获取商品的id和商品的数量
        var sku_id = $(this).attr("sku_id"),
            count = $(this).val();

        // 校验参数
        if (isNaN(count) || count.trim().length==0 || parseInt(count)<=0){
            // 设置商品的数目为用户输入之前的数目
            $(this).val(pre_count)
            return
        }

        // 更新购物车记录
        update_remote_cart_info(sku_id, count);
        // 判断更新是否成功
        if (error_update == false){
            // 更新成功
            // 获取页面上所有商品的数目
            var all_len = $('.cart_list_td').length;
            // 获取页面上所有勾选商品的数目
            var checked_len = $('.cart_list_td').find(':checked').length;
            is_checked = true;
            if (all_len > checked_len){
                is_checked = false;
            }
            $('.settlements').find(':checkbox').prop('checked', is_checked);

            // 更新商品总数
            $(this).prev().val(count);
            update_page_info();

        }
    })

        // 删除购物车中的记录
    $('.cart_list_td').children('.col08').children('a').click(function () {
        // 获取对应商品的id
        var sku_id = $(this).parents('ul').find('.num_show').attr('sku_id'),
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
        // 组织参数
        var params = {'sku_id':sku_id, 'csrfmiddlewaretoken':csrf};
        // 获取商品所在的ul元素
        var sku_ul = $(this).parents('ul');
        // 发起ajax post请求， 访问/cart/delete, 传递参数:sku_id
        $.post('/cart/delete', params, function (data) {
            if (data.res == 3){
                // 删除成功，删除页面上商品所在的ul元素
                sku_ul.remove();
                // 获取sku_ul中商品的选中状态
                is_checked = sku_ul.find(':checkbox').prop('checked')
                if (is_checked){
                    // 重新设置页面上购物车中商品的总件数
                    $('.total_count').children('em').text(data.total_count)
                    // 更新页面信息
                    update_page_info()
                }
                // 重新设置页面上购物车中商品的总件数
                $('.total_count').children('em').text(data.total_count)
            }
            else{
                alert(data.errmsg)
            }
        })
    })

    </script>

	{% block footer %}
        {{ block.super }}
	{% endblock %}